/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jym.ferreteria.datasource;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import jym.ferreteria.clases.Controlador;

import jym.ferreteria.gui.dialogs.SeleccionarProductoRegularizacionDialog;
import jym.ferreteria.gui.dialogs.SeleccionarProveedorDialog;

public class FrmEstadisticoVentas extends javax.swing.JInternalFrame {

    private Controlador control = new Controlador();
    private SeleccionarProveedorDialog seleccionarProveedor = null;

    private SeleccionarProductoRegularizacionDialog seleccionarProductoRegularizacion;
    private String idProducto;
    
    public FrmEstadisticoVentas() {
        initComponents();
        txtFechaDesde.setDate(new Date());
       cargarCombo();
        this.setFrameIcon(new ImageIcon(this.getClass().getResource(Controlador.ICON_PATH)));
    }
    
    public void cargarCombo(){
        
        cbsPeriodo.setEnabled(true);
        cbsNumDatos.setEnabled(true);
    
            cbsPeriodo.removeAllItems();
            
            cbsPeriodo.addItem("Diario");
            cbsPeriodo.addItem("Mensual");
            cbsPeriodo.addItem("Anual");
            
            cbsPeriodo.setSelectedIndex(0);
            
            cbsNumDatos.removeAllItems();
            
            cbsNumDatos.addItem("5");
            cbsNumDatos.addItem("6");
            cbsNumDatos.addItem("7");
            cbsNumDatos.addItem("8");
            cbsNumDatos.addItem("9");
            cbsNumDatos.addItem("10");
            cbsNumDatos.addItem("11");
            cbsNumDatos.addItem("12");
            cbsNumDatos.addItem("13");
            cbsNumDatos.addItem("14");
            cbsNumDatos.addItem("15");
            
            cbsNumDatos.setSelectedIndex(0);
    }
    
            private void cargarDatos() {
        Map map = new HashMap();

        Date fechaIni=new Date();
        int Periodo=cbsPeriodo.getSelectedIndex();
        int NumDatos=Integer.parseInt(cbsNumDatos.getSelectedItem().toString());
        
        boolean b=false;
        //producto vacio

            if (txtFechaDesde.getDate() == null ) {//sin fechas

                b=false;
            } else {//con fechas
               b=true;
                fechaIni =txtFechaDesde.getDate();

            }
       
        map.put("fechaIni", fechaIni);
        System.out.println(fechaIni);
        map.put("numDatos",NumDatos);
        
        if(b){
            
            if(Periodo==0){
             control.showReportDialog("Reporte Analisis Ventas Diario", "reporteEstadisticoDiario", map);
             }
            if(Periodo==1){
             control.showReportDialog("Reporte Analisis Ventas Diario", "reporteEstadisticoMensual", map);
             }
            if(Periodo==2){
             control.showReportDialog("Reporte Analisis Ventas Diario", "reporteEstadisticoAnual", map);
             }

        }
        else{
            JOptionPane.showMessageDialog(null, "Para que el Reporte sea Impreso es necesario indicar la fecha Inicial de Análisis");
        }


    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFechaDesde = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        cbsPeriodo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbsNumDatos = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte Estadístico de Ventas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Fecha Inicial de Análisis");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Periodo de Análisis:");

        cbsPeriodo.setEnabled(false);
        cbsPeriodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbsPeriodoItemStateChanged(evt);
            }
        });
        cbsPeriodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbsPeriodoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbsPeriodoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbsPeriodoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbsPeriodoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbsPeriodoMouseReleased(evt);
            }
        });
        cbsPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsPeriodoActionPerformed(evt);
            }
        });
        cbsPeriodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbsPeriodoKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Número de Datos:");

        cbsNumDatos.setEnabled(false);
        cbsNumDatos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbsNumDatosItemStateChanged(evt);
            }
        });
        cbsNumDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbsNumDatosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbsNumDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbsNumDatosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbsNumDatosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbsNumDatosMouseReleased(evt);
            }
        });
        cbsNumDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsNumDatosActionPerformed(evt);
            }
        });
        cbsNumDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbsNumDatosKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbsPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtFechaDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbsNumDatos, 0, 209, Short.MAX_VALUE)))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbsPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbsNumDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/Print.png"))); // NOI18N
        jButton1.setMnemonic('I');
        jButton1.setText("Imprimir");
        jButton1.setPreferredSize(new java.awt.Dimension(114, 33));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/cancel.png"))); // NOI18N
        jButton4.setMnemonic('C');
        jButton4.setText("Cancelar");
        jButton4.setPreferredSize(new java.awt.Dimension(114, 33));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/salir.png"))); // NOI18N
        jButton3.setMnemonic('S');
        jButton3.setText("Salir");
        jButton3.setPreferredSize(new java.awt.Dimension(90, 33));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      cargarDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        cargarCombo();
        txtFechaDesde.setDate(new Date());
  

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbsPeriodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbsPeriodoItemStateChanged
        //cargarProductos(); // TODO add your handling code here:
    }//GEN-LAST:event_cbsPeriodoItemStateChanged

    private void cbsPeriodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbsPeriodoMouseClicked
        // cargarProductos();   // TODO add your handling code here:
    }//GEN-LAST:event_cbsPeriodoMouseClicked

    private void cbsPeriodoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbsPeriodoMouseEntered
        //cargarProductos();        // TODO add your handling code here:
    }//GEN-LAST:event_cbsPeriodoMouseEntered

    private void cbsPeriodoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbsPeriodoMouseExited
        //cargarProductos();    // TODO add your handling code here:
    }//GEN-LAST:event_cbsPeriodoMouseExited

    private void cbsPeriodoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbsPeriodoMousePressed
        //cargarProductos();        // TODO add your handling code here:
    }//GEN-LAST:event_cbsPeriodoMousePressed

    private void cbsPeriodoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbsPeriodoMouseReleased
        //cargarProductos();        // TODO add your handling code here:
    }//GEN-LAST:event_cbsPeriodoMouseReleased

    private void cbsPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsPeriodoActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_cbsPeriodoActionPerformed

    private void cbsPeriodoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbsPeriodoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsPeriodoKeyPressed

    private void cbsNumDatosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbsNumDatosItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsNumDatosItemStateChanged

    private void cbsNumDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbsNumDatosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsNumDatosMouseClicked

    private void cbsNumDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbsNumDatosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsNumDatosMouseEntered

    private void cbsNumDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbsNumDatosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsNumDatosMouseExited

    private void cbsNumDatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbsNumDatosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsNumDatosMousePressed

    private void cbsNumDatosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbsNumDatosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsNumDatosMouseReleased

    private void cbsNumDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsNumDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsNumDatosActionPerformed

    private void cbsNumDatosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbsNumDatosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsNumDatosKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbsNumDatos;
    private javax.swing.JComboBox cbsPeriodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser txtFechaDesde;
    // End of variables declaration//GEN-END:variables
}
