/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jym.ferreteria.gui.dialogs;

import java.awt.Color;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jym.ferreteria.clases.Controlador;

/**
 *
 * @author Omr
 */
public class FacturarEntradaDeStockDialog extends javax.swing.JDialog {

        private Controlador control = new Controlador();
        private String entrada = null;
        private String resultado = "error";
        private Map map = new HashMap();

        /**
         * Creates new form FacturarEntradaDeStock
         *
         * @param parent
         * @param modal
         */
        public FacturarEntradaDeStockDialog(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
                getContentPane().setBackground(new Color(185, 204, 130));
                setIconImage(new ImageIcon(getClass().getResource(Controlador.ICON_PATH)).getImage());
                control.fillComboBox("SELECT `idTipoComprobante`, `nombre` FROM `tipocomprobante` WHERE `paraVenta`=FALSE and (idTipoComprobante=4 or idTipoComprobante=5 or idTipoComprobante=9) ORDER BY `nombre`;", cboComprobante, map);

                txtFecha.setDate(new Date());
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                txtSerie = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                txtFecha = new com.toedter.calendar.JDateChooser();
                txtNumero = new javax.swing.JTextField();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jLabel4 = new javax.swing.JLabel();
                txtObservaciones = new javax.swing.JTextField();
                cboComprobante = new javax.swing.JComboBox();
                jLabel5 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Facturar");
                setType(java.awt.Window.Type.UTILITY);

                jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                jLabel1.setText("Serie: ");
                jLabel1.setName("jLabel1"); // NOI18N

                txtSerie.setName("txtSerie"); // NOI18N
                txtSerie.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                txtSerieKeyTyped(evt);
                        }
                });

                jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                jLabel2.setText("Número: ");
                jLabel2.setName("jLabel2"); // NOI18N

                jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                jLabel3.setText("Fecha: ");
                jLabel3.setName("jLabel3"); // NOI18N

                txtFecha.setName("txtFecha"); // NOI18N

                txtNumero.setName("txtNumero"); // NOI18N
                txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                txtNumeroKeyTyped(evt);
                        }
                });

                jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/salir.png"))); // NOI18N
                jButton1.setText("Salir");
                jButton1.setName("jButton1"); // NOI18N
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/registrar.png"))); // NOI18N
                jButton2.setText("Aceptar");
                jButton2.setName("jButton2"); // NOI18N
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                jLabel4.setText("Observaciones: ");
                jLabel4.setName("jLabel4"); // NOI18N

                txtObservaciones.setName("txtObservaciones"); // NOI18N

                cboComprobante.setName("cboComprobante"); // NOI18N

                jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                jLabel5.setText("Comprobante: ");
                jLabel5.setName("jLabel5"); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cboComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cboComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                resultado = "error";
                dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                aceptar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSerieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerieKeyTyped
                control.Solonumeros(evt);
    }//GEN-LAST:event_txtSerieKeyTyped

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
                control.Solonumeros(evt);
    }//GEN-LAST:event_txtNumeroKeyTyped

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(FacturarEntradaDeStockDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(FacturarEntradaDeStockDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(FacturarEntradaDeStockDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(FacturarEntradaDeStockDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
        //</editor-fold>

                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                FacturarEntradaDeStockDialog dialog = new FacturarEntradaDeStockDialog(new javax.swing.JFrame(), true);
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JComboBox cboComprobante;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private com.toedter.calendar.JDateChooser txtFecha;
        private javax.swing.JTextField txtNumero;
        private javax.swing.JTextField txtObservaciones;
        private javax.swing.JTextField txtSerie;
        // End of variables declaration//GEN-END:variables

        public void setEntrada(String idEntrada) {
                entrada = idEntrada;
        }

        public String getResultado() {
                return resultado;
        }

        private void aceptar() {
                if (txtSerie.getText().trim().length() > 0 && txtNumero.getText().trim().length() > 0) {
                        if (txtFecha.getDate() != null) {
                                String idProveedor = control.DevolverRegistroDto("SELECT `idProveedor` FROM `entradastock` WHERE `idEntradaStock`='" + entrada + "';", 1);
                                String total = control.ejecutarMsg(String.format("SELECT IFNULL(SUM(`cantidad`*`costo`),0.00) FROM `detalleentradastock` WHERE `idEntradaStock`=%s;", entrada));
                                control.CrearRegistro(String.format("INSERT INTO facturaproveedor VALUES(NULL,%s,'%s','%s','%s',0,%s,'%s',%s,%s,true);", idProveedor, txtSerie.getText(), txtNumero.getText(),
                                        control.Formato_Amd(txtFecha.getDate()), total, txtObservaciones.getText(), map.get(cboComprobante.getSelectedIndex()), total));
                                String id = control.DevolverRegistroDto("SELECT LAST_INSERT_ID();", 1);
                                if (id.equals("0")) {
                                        id = control.DevolverRegistroDto("SELECT MAX(`idFacturaProveedor`) FROM `facturaproveedor`;", 1);
                                }
                                if (id != null && !id.equals("")) {
                                        control.EditarRegistro(String.format("UPDATE entradastock e SET e.`facturado`=true, e.`idFacturaProveedor`=%s WHERE e.`idEntradaStock`=%s;", id, entrada));
                                        resultado = "success";
                                        if (JOptionPane.showConfirmDialog(this, "Se ha generado comprobante del proveedor, ¿Desea visualizarla?", "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                                                Map map = new HashMap();
                                                map.put("idFacturaProveedor", id);
                                                control.showReportDialog("Factura de proveedor", "FacturaProveedor", map);
                                        }
                                        this.dispose();
                                } else {
                                        JOptionPane.showMessageDialog(this, "Ocurrió un error al procesar los datos");
                                }

                        } else {
                                JOptionPane.showMessageDialog(this, "Debe indicar la fecha de facturación", "Aviso", JOptionPane.WARNING_MESSAGE);
                        }
                } else {
                        JOptionPane.showMessageDialog(this, "Ingrese la serie y el número de la factura del proveedor", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
        }
}
