/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jym.ferreteria.gui.dialogs;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import jym.ferreteria.clases.Controlador;

/**
 *
 * @author Omr
 */
public class RegistrarNuevoClienteDialog extends javax.swing.JDialog {

        private Controlador control = new Controlador();
        private String[] datos;

        /**
         * Creates new form NuevoCliente
         */
        public RegistrarNuevoClienteDialog(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRucDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cboTipoCliente = new javax.swing.JComboBox();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtmail1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtmail2 = new javax.swing.JTextField();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Cliente");
        addWindowFocusListener(formListener);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Tipo Cliente:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("RUC / DNI: ");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nombres: ");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Dirección: ");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Teléfono: ");
        jLabel5.setName("jLabel5"); // NOI18N

        txtRucDni.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtRucDni.setName("txtRucDni"); // NOI18N
        txtRucDni.addKeyListener(formListener);

        txtNombre.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtNombre.setName("txtNombre"); // NOI18N
        txtNombre.addKeyListener(formListener);

        txtDireccion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtDireccion.setName("txtDireccion"); // NOI18N
        txtDireccion.addKeyListener(formListener);

        txtTelefono.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtTelefono.setName("txtTelefono"); // NOI18N
        txtTelefono.addKeyListener(formListener);

        cboTipoCliente.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cboTipoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Natural", "Juridico", "Carnet de Extranjería", "Pasaporte", "Cédula Diplomática" }));
        cboTipoCliente.setName("cboTipoCliente"); // NOI18N
        cboTipoCliente.addKeyListener(formListener);

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(formListener);

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/Actions-document-save-icon.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(formListener);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Correo 1:");
        jLabel6.setName("jLabel6"); // NOI18N

        txtmail1.setName("txtmail1"); // NOI18N
        txtmail1.addActionListener(formListener);
        txtmail1.addKeyListener(formListener);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Correo 2:");
        jLabel10.setName("jLabel10"); // NOI18N

        txtmail2.setName("txtmail2"); // NOI18N
        txtmail2.addActionListener(formListener);
        txtmail2.addKeyListener(formListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboTipoCliente, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRucDni)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                            .addComponent(txtTelefono)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmail1)
                            .addComponent(txtmail2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRucDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txtmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(txtmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.KeyListener, java.awt.event.WindowFocusListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == btnCancelar) {
                RegistrarNuevoClienteDialog.this.btnCancelarActionPerformed(evt);
            }
            else if (evt.getSource() == btnGuardar) {
                RegistrarNuevoClienteDialog.this.btnGuardarActionPerformed(evt);
            }
            else if (evt.getSource() == txtmail1) {
                RegistrarNuevoClienteDialog.this.txtmail1ActionPerformed(evt);
            }
            else if (evt.getSource() == txtmail2) {
                RegistrarNuevoClienteDialog.this.txtmail2ActionPerformed(evt);
            }
        }

        public void keyPressed(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == txtRucDni) {
                RegistrarNuevoClienteDialog.this.txtRucDniKeyPressed(evt);
            }
            else if (evt.getSource() == txtNombre) {
                RegistrarNuevoClienteDialog.this.txtNombreKeyPressed(evt);
            }
            else if (evt.getSource() == txtDireccion) {
                RegistrarNuevoClienteDialog.this.txtDireccionKeyPressed(evt);
            }
            else if (evt.getSource() == txtTelefono) {
                RegistrarNuevoClienteDialog.this.txtTelefonoKeyPressed(evt);
            }
            else if (evt.getSource() == cboTipoCliente) {
                RegistrarNuevoClienteDialog.this.cboTipoClienteKeyPressed(evt);
            }
            else if (evt.getSource() == txtmail1) {
                RegistrarNuevoClienteDialog.this.txtmail1KeyPressed(evt);
            }
            else if (evt.getSource() == txtmail2) {
                RegistrarNuevoClienteDialog.this.txtmail2KeyPressed(evt);
            }
        }

        public void keyReleased(java.awt.event.KeyEvent evt) {
        }

        public void keyTyped(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == txtRucDni) {
                RegistrarNuevoClienteDialog.this.txtRucDniKeyTyped(evt);
            }
            else if (evt.getSource() == txtmail1) {
                RegistrarNuevoClienteDialog.this.txtmail1KeyTyped(evt);
            }
            else if (evt.getSource() == txtmail2) {
                RegistrarNuevoClienteDialog.this.txtmail2KeyTyped(evt);
            }
        }

        public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            if (evt.getSource() == RegistrarNuevoClienteDialog.this) {
                RegistrarNuevoClienteDialog.this.formWindowGainedFocus(evt);
            }
        }

        public void windowLostFocus(java.awt.event.WindowEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
                datos = null;
                this.dispose();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
                guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtRucDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucDniKeyPressed
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        if (txtRucDni.getText().trim().length() >= 8) {
                                txtNombre.grabFocus();
                        }
                }
    }//GEN-LAST:event_txtRucDniKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        if (txtNombre.getText().trim().length() > 0) {
                                txtDireccion.grabFocus();
                        }
                }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        txtTelefono.grabFocus();
                }
    }//GEN-LAST:event_txtDireccionKeyPressed

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        btnGuardar.grabFocus();
                }
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void cboTipoClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboTipoClienteKeyPressed
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        txtRucDni.grabFocus();
                }
    }//GEN-LAST:event_cboTipoClienteKeyPressed

    private void txtRucDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucDniKeyTyped
               /* control.Solonumeros(evt);
                control.Longitudtx(txtRucDni, evt, 11);*/
               
                int a=cboTipoCliente.getSelectedIndex();
        
        if(a<2){
        control.Solonumeros(evt);
           if(a==0){
               control.Longitudtx(txtRucDni, evt, 8);
           }else if(a==1){
               control.Longitudtx(txtRucDni, evt, 11);
           }
        }else if(a==2 || a==3){
            control.Longitudtx(txtRucDni, evt, 12);
        }else if(a==4){
            control.Longitudtx(txtRucDni, evt, 15);
        }
    }//GEN-LAST:event_txtRucDniKeyTyped

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
                cboTipoCliente.requestFocus();
    }//GEN-LAST:event_formWindowGainedFocus

    private void txtmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmail1ActionPerformed

    private void txtmail1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmail1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmail1KeyPressed

    private void txtmail1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmail1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmail1KeyTyped

    private void txtmail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmail2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmail2ActionPerformed

    private void txtmail2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmail2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmail2KeyPressed

    private void txtmail2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmail2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmail2KeyTyped

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(RegistrarNuevoClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(RegistrarNuevoClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(RegistrarNuevoClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(RegistrarNuevoClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
        //</editor-fold>

                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                RegistrarNuevoClienteDialog dialog = new RegistrarNuevoClienteDialog(new javax.swing.JFrame(), true);
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cboTipoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRucDni;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtmail1;
    private javax.swing.JTextField txtmail2;
    // End of variables declaration//GEN-END:variables

        private void guardar() {
                String id = "";
                String nombre = "";
                
            int num=txtRucDni.getText().trim().length();
            int tipo=cboTipoCliente.getSelectedIndex();
            boolean resp=false;
            String msj="";
            if(tipo==0){
                if(num==8){
                    resp=true;
                }else{
                    msj="EL DNI no cuenta con un formato válido, consigne 08 dígitos numéricos";
                }
            }else if(tipo==1){
                if(num==11){
                    resp=true;
                }else{
                    msj="EL número RUC no cuenta con un formato válido, consigne 11 dígitos numéricos";
                }
            }else if(tipo==2){
                if(num>=8){
                    resp=true;
                }else{
                    msj="EL formato del Carne de Extranjería no es el correcto";
                }
            }else if(tipo==3){
                if(num>=8){
                    resp=true;
                }else{
                    msj="EL formato del Pasaporte no es el correcto";
                }
            }else if(tipo==4){
                if(num>=8){
                    resp=true;
                }else{
                    msj="EL formato de la cédula diplomática no es la correcta";
                }
            }
            
            

                if (resp) {
                        datos = new String[5];
                        String data[] = control.cargarRegistro(String.format("SELECT `idCliente`, `nomcte` FROM `cliente` WHERE `dniRuc`='%s' AND `dniRuc`<>'';", txtRucDni.getText()), 2);
                        if (data == null) {
                                id = "" + control.executeAndGetId(String.format("INSERT INTO cliente VALUES(NULL,'%s','%s','%s','%s','%s','%s','%s');", txtNombre.getText().trim(), cboTipoCliente.getSelectedItem().toString(), txtDireccion.getText(), txtRucDni.getText(), txtTelefono.getText(),txtmail1.getText(),txtmail2.getText()));
                                nombre = txtNombre.getText();
                        } else {
                                id = data[0];
                                nombre = data[1];
                        }
                        datos[0] = id;
                        datos[1] = txtRucDni.getText();
                        datos[2] = nombre;
                        datos[3] = txtDireccion.getText();
                        datos[4] = cboTipoCliente.getSelectedItem().toString();
                        this.dispose();
                } else {
                        JOptionPane.showMessageDialog(this, msj);
                }

        }

        public String[] getDatos() {
                return datos;
        }

}
