/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jym.ferreteria.gui.dialogs;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import jym.ferreteria.clases.Controlador;
import jym.ferreteria.gui.internalframes.FrmGestionRegularizacionesDeStock;
import jym.ferreteria.renders.CustomTableModel;
import jym.ferreteria.renders.LabelRenderer;

/**
 *
 * @author Omr
 */
public class SeleccionarProductoRegularizacionDialog extends javax.swing.JDialog {

        private CustomTableModel productosModel = new CustomTableModel();
        private CustomTableModel productosModel2 = new CustomTableModel();
        //private CustomTableModel productosAlmacenModel = new CustomTableModel();
        private Controlador control = new Controlador();
        private String[] datos;
        private int selectedRow;
        private List<double[]> lista = new ArrayList();
        private DecimalFormat format = new DecimalFormat("00.00");
        private FrmGestionRegularizacionesDeStock regularizacionStock = null;
        private String idAlmacen;

        /**
         * Creates new form SeleccionarProducto
         */
        public SeleccionarProductoRegularizacionDialog(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
                setIconImage(new ImageIcon(getClass().getResource(Controlador.ICON_PATH)).getImage());
                productosModel.setColumnIdentifiers(new String[]{"Id", "Descripción producto", "Unidad", "Pv. x menor", "Pv. x mayor", "P. Compra"});
                productosModel2.setColumnIdentifiers(new String[]{"Id", "Descripción producto", "Unidad", "Pv. x menor", "Pv. x mayor", "P. Compra", "Cantidad"});
                tablaProductos.setModel(productosModel);
                control.hideTableColumn(tablaProductos, 0);
                control.tableWidthColumn(tablaProductos, 500, 1);
                control.tableWidthColumn(tablaProductos, 80, 3, 4, 5);

                LabelRenderer labelRenderer = new LabelRenderer(SwingConstants.RIGHT);
                tablaProductos.getColumnModel().getColumn(3).setCellRenderer(labelRenderer);
                tablaProductos.getColumnModel().getColumn(4).setCellRenderer(labelRenderer);
                tablaProductos.getColumnModel().getColumn(5).setCellRenderer(labelRenderer);
                tablaProductos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

                        @Override
                        public void valueChanged(ListSelectionEvent e) {
                                btnSeleccionar.setEnabled(true);
                        }
                });

        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblBuscar = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                tablaProductos = new javax.swing.JTable();
                btnSeleccionar = new javax.swing.JButton();
                jButton1 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Seleccionar productos");

                lblBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                lblBuscar.setText("Buscar");
                lblBuscar.setName("lblBuscar"); // NOI18N

                jTextField1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                jTextField1.setName("jTextField1"); // NOI18N
                jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                jTextField1KeyPressed(evt);
                        }
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                jTextField1KeyReleased(evt);
                        }
                });

                jScrollPane1.setName("jScrollPane1"); // NOI18N

                tablaProductos.setAutoCreateRowSorter(true);
                tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tablaProductos.setName("tablaProductos"); // NOI18N
                tablaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                tablaProductos.getTableHeader().setReorderingAllowed(false);
                tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tablaProductosMouseClicked(evt);
                        }
                });
                tablaProductos.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                tablaProductosKeyPressed(evt);
                        }
                });
                jScrollPane1.setViewportView(tablaProductos);

                btnSeleccionar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/registrar.png"))); // NOI18N
                btnSeleccionar.setMnemonic('S');
                btnSeleccionar.setText("Seleccionar");
                btnSeleccionar.setName("btnSeleccionar"); // NOI18N
                btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSeleccionarActionPerformed(evt);
                        }
                });

                jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/salir.png"))); // NOI18N
                jButton1.setMnemonic('C');
                jButton1.setText("Cerrar");
                jButton1.setName("jButton1"); // NOI18N
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblBuscar)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(btnSeleccionar))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
                if (evt.getClickCount() > 1) {
                        seleccionarProducto();
                }
    }//GEN-LAST:event_tablaProductosMouseClicked

        private void aplicarFormato() {

                control.hideTableColumn(tablaProductos, 0);
                control.tableWidthColumn(tablaProductos, 500, 1);
                control.tableWidthColumn(tablaProductos, 80, 3, 4, 5);
                LabelRenderer labelRenderer = new LabelRenderer(SwingConstants.RIGHT);
                tablaProductos.getColumnModel().getColumn(3).setCellRenderer(labelRenderer);
                tablaProductos.getColumnModel().getColumn(4).setCellRenderer(labelRenderer);
                tablaProductos.getColumnModel().getColumn(5).setCellRenderer(labelRenderer);

        }

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
                if (tablaProductos.getColumnCount() == 6) {
                        cargarProductos();
                } else {
                        cargarProductosTraspasoSalida(idAlmacen);
                }
                btnSeleccionar.setEnabled(false);

    }//GEN-LAST:event_jTextField1KeyReleased

    private void tablaProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaProductosKeyPressed

    }//GEN-LAST:event_tablaProductosKeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        if (productosModel.getRowCount() > 0) {
                                tablaProductos.getSelectionModel().setSelectionInterval(0, 0);
                                tablaProductos.requestFocus();
                        }
                }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                datos = null;
                dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
                seleccionarProducto();

    }//GEN-LAST:event_btnSeleccionarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(SeleccionarProductoRegularizacionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(SeleccionarProductoRegularizacionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(SeleccionarProductoRegularizacionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(SeleccionarProductoRegularizacionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
        //</editor-fold>

                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                SeleccionarProductoRegularizacionDialog dialog = new SeleccionarProductoRegularizacionDialog(new javax.swing.JFrame(), true);
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnSeleccionar;
        private javax.swing.JButton jButton1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JLabel lblBuscar;
        private javax.swing.JTable tablaProductos;
        // End of variables declaration//GEN-END:variables

        public void setProductosRegularizacion(String idregularizacion, String Almacen1, String Almacen2, String tipoRegularizacion) {

                if (idregularizacion != null) {
                        if (tipoRegularizacion.equals("Entrada")) {
                                tablaProductos.setModel(productosModel);
                                cargarProductos();
                        } else if (tipoRegularizacion.equals("Salida") || tipoRegularizacion.equals("Traspaso")) {
                                tablaProductos.setModel(productosModel2);
                                String idAlmacenS = control.DevolverRegistroDto("select * from almacen where nombre='" + Almacen2 + "';", 1);
                                cargarProductosTraspasoSalida(idAlmacenS);
                        }
                }
        }

        private void cargarProductos() {
                this.aplicarFormato();
                String text = jTextField1.getText();
                control.Sql = "select  `ID`, concat(`Producto`,' ',`marca`), `Unidad`,`Precxmenor`, `Precxmayor`, `precioCompra`  from Vta_Catalogo where `Codigo` like '%" + text
                        + "%' or Producto like'%" + text + "%' or marca like '%" + text
                        + "%' or Marca like'%" + text + "%'order by Producto;";

                control.LlenarJTabla(productosModel, control.Sql, 6);
                //control.LimTabla(productosAlmacenModel);
                btnSeleccionar.setEnabled(false);
                selectedRow = -1;
        }

        private void cargarProductosTraspasoSalida(String idAlmacen) {
                this.idAlmacen = idAlmacen;
                this.aplicarFormato();
                String text = jTextField1.getText();
                control.Sql = "select  `ID`, concat(`Producto`,' ',`Descripcion`), `Unidad`,`Precxmenor`, `Precxmayor`, `precioCompra`,s.cantidadDisponible  from Vta_Catalogo v, stock s "
                        + "WHERE s.`idProducto`=v.ID AND s.`idAlmacen`='" + idAlmacen + "' and ( `Codigo` like '%" + text
                        + "%' or Producto like'%" + text + "%' or Descripcion like '%" + text
                        + "%' or Marca like'%" + text + "%')order by Producto";

                control.LlenarJTabla(productosModel2, control.Sql, 7);
                //control.LimTabla(productosAlmacenModel);
                btnSeleccionar.setEnabled(false);
                selectedRow = -1;
        }

        private void seleccionarProducto() {
                int row = tablaProductos.getSelectedRow();
                //JOptionPane.showMessageDialog(rootPane, tablaProductos.getColumnCount());

                if (6 == tablaProductos.getColumnCount()) {
                        datos = new String[7];
            //String as= productosModel.getValueAt(row, 0).toString();
                        //String as1= productosModel.getValueAt(row, 1).toString();
                        //JOptionPane.showMessageDialog(rootPane, as+"--"+as1);
                        datos[0] = productosModel.getValueAt(row, 0).toString();//id
                        datos[1] = productosModel.getValueAt(row, 1).toString();//nombre
                        datos[2] = productosModel.getValueAt(row, 2).toString();//unidad
                        datos[3] = productosModel.getValueAt(row, 3).toString();//precio por menor
                        datos[4] = productosModel.getValueAt(row, 4).toString();//precio por mayor
                        datos[5] = productosModel.getValueAt(row, 5).toString();//Stock
                        datos[6] = "";
                } else {
                        datos = new String[7];
            //String as= productosModel2.getValueAt(row, 0).toString();
                        //String as1= productosModel2.getValueAt(row, 1).toString();
                        //JOptionPane.showMessageDialog(rootPane, as+"--"+as1);
                        datos[0] = productosModel2.getValueAt(row, 0).toString();//id
                        datos[1] = productosModel2.getValueAt(row, 1).toString();//nombre
                        datos[2] = productosModel2.getValueAt(row, 2).toString();//unidad
                        datos[3] = productosModel2.getValueAt(row, 3).toString();//precio por menor
                        datos[4] = productosModel2.getValueAt(row, 4).toString();//precio por mayor
                        datos[5] = productosModel2.getValueAt(row, 5).toString();//precio de compra
                        datos[6] = productosModel2.getValueAt(row, 6).toString();//Stock
                }

                this.dispose();
        }

        /**
         *
         * @return [id, nombre, unidad, precio por menor, precio por mayor,
         * precio compra, stock]
         */
        public String[] getDatos() {
                return datos;
        }

        @Override
        public void setVisible(boolean b) {
                datos = null;
                super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
        }

        public void setLista(List<double[]> lista) {
                this.lista = lista;
                cargarProductos();
        }
}
