/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jym.ferreteria.gui.panels;

import javax.swing.JTable;
import jym.ferreteria.gui.internalframes.FrmRegistrarGastos;
import jym.ferreteria.renders.CustomTableModel;

/**
 *
 * @author Omr
 */
public class PanelGastoMes extends javax.swing.JPanel {

    private CustomTableModel model = new CustomTableModel();

    /**
     * Creates new form PanelGastoMes
     */
    public PanelGastoMes() {
        initComponents();
        model.setColumnIdentifiers(new String[]{"ID", "Clasificación", "Concepto", "Fecha", "Detalle", "Importe"});
        tablaGastos.setModel(model);
        FrmRegistrarGastos.control.hideTableColumn(tablaGastos, 0);
        FrmRegistrarGastos.control.tableMaxWidthColumn(tablaGastos, 100, 5);
        FrmRegistrarGastos.control.tableMaxWidthColumn(tablaGastos, 150, 3);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGastos = new javax.swing.JTable();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablaGastos.setAutoCreateRowSorter(true);
        tablaGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaGastos.setName("tablaGastos"); // NOI18N
        tablaGastos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaGastos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaGastos;
    // End of variables declaration//GEN-END:variables

    public void setPeriodo(int year, int month) {

        FrmRegistrarGastos.control.Sql = "SELECT g.`idGastos` , c.`nombre`, co.`nombre`, CONCAT(diaIndice(WEEKDAY(g.`fecha`)),' ',date_format(g.`fecha`,'%d/%m/%Y')), g.`detalle`, format(g.`importe`,2) FROM clasificaciongastos c, conceptogastos co, gastos g WHERE c.`idClasificacionGastos`=co.`idClasificacionGastos` AND co.`idConceptoGastos`=g.`idConceptoGastos` AND g.`anio`='" + year + "' AND g.`mes`='" + month + "';";
        System.out.println(FrmRegistrarGastos.control.Sql);
        FrmRegistrarGastos.control.LlenarJTabla(model, FrmRegistrarGastos.control.Sql, 6);
    }

    public JTable getTablaGastos() {
        return tablaGastos;
    }

}
