/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmGestionPermiso.java
 *
 * Created on 06-feb-2014, 17:23:44
 */
package jym.ferreteria.gui.internalframes;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jym.ferreteria.clases.Controlador;
import jym.ferreteria.renders.CustomTableModel;

/**
 *
 * @author Silva
 */
public class FrmGestionPermiso extends javax.swing.JInternalFrame {

    Controlador control = new Controlador();
    CustomTableModel modelo = new CustomTableModel();
    String codper = "";

    /**
     * Creates new form CrearPresmiso
     */
    public FrmGestionPermiso() {
        initComponents();
        this.setTitle("Permisos");
        this.setFrameIcon(new ImageIcon(this.getClass().getResource(Controlador.ICON_PATH)));
        tbPermisos.setModel(modelo);
        modelo.setColumnIdentifiers(new String[]{"Item", "Permiso"});
        tbPermisos.getColumnModel().getColumn(0).setMaxWidth(0);
        tbPermisos.getColumnModel().getColumn(0).setMinWidth(0);
        tbPermisos.getColumnModel().getColumn(0).setPreferredWidth(0);
        MostrarCliente();
    }

    public void MostrarCliente() {
        BuscarCliente();
    }

    public void BuscarCliente() {
        control.Sql = "SELECT * FROM Permisos where Descripcion like'"
                + txtBuscarPermisos.getText() + "%';";
        control.LlenarJTabla(modelo, control.Sql, 2);

        //    JOptionPane.showMessageDialog(null,control.Sql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Cancelar() {
        txtPermisos.setText("");
        txtBuscarPermisos.setText("");
        bCrear.setText("Crear");
        bModificar.setText("Editar");
        bCrear.setEnabled(true);
        bModificar.setEnabled(false);
    }

    public void CrearPermisos() {
        if (bCrear.getText().compareTo("Crear") == 0) {
            if (txtPermisos.getText().trim().length() > 0) {
                control.Sql = "insert into permisos (Descripcion) values ('" + txtPermisos.getText() + "');";
                control.CrearRegistro(control.Sql);
                txtPermisos.setText("");
                txtPermisos.grabFocus();
                control.LimTabla(modelo);
                MostrarCliente();
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese el Nuevo Permiso!!");
                txtPermisos.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "fds");
        }
    }

    public void EditarPermiso() {
        if (tbPermisos.getSelectedRowCount() == 1) {
            if (bModificar.getText().compareTo("Editar") == 0) {
                txtPermisos.setText(modelo.getValueAt(tbPermisos.getSelectedRow(), 1).toString());
                codper = modelo.getValueAt(tbPermisos.getSelectedRow(), 0).toString();
                bCrear.setEnabled(false);
                bEliminar.setEnabled(false);
                bModificar.setText("Grabar");
            } else {
                if (txtPermisos.getText().trim().length() > 0) {
                    control.Sql = "update permisos set Descripcion='" + txtPermisos.getText() + "' where idpermisos='" + codper + "';";
                    control.EditarRegistro(control.Sql);
                    control.LimTabla(modelo);
                    MostrarCliente();
                    bCrear.setEnabled(true);
                    bEliminar.setEnabled(true);
                    bModificar.setText("Editar");
                    txtPermisos.setText("");
                    txtPermisos.grabFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Tiene que Ingresar el Permiso");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione un permiso para Editarlo");
        }
    }

    public void EliminarPermiso() {
        if (tbPermisos.getSelectedRowCount() == 1) {
            if (JOptionPane.showConfirmDialog(null, "Desea  Eliminar este Permiso!!", "", JOptionPane.YES_NO_OPTION) == 0) {
                control.Sql = "delete from permisos where idpermisos='" + modelo.getValueAt(tbPermisos.getSelectedRow(), 0).toString() + "';";
                control.EliminarRegistro(control.Sql);
                control.LimTabla(modelo);
                MostrarCliente();
                txtPermisos.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un permiso para eliminar!!");
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPermisos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        bCrear = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPermisos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarPermisos = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar Permisos");

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tbPermisos.setForeground(new java.awt.Color(0, 51, 102));
        tbPermisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbPermisos.setName("tbPermisos"); // NOI18N
        tbPermisos.getTableHeader().setReorderingAllowed(false);
        tbPermisos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPermisosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPermisos);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N

        bCrear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bCrear.setForeground(new java.awt.Color(0, 51, 102));
        bCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/Accept.png"))); // NOI18N
        bCrear.setText("Crear");
        bCrear.setName("bCrear"); // NOI18N
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        bModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bModificar.setForeground(new java.awt.Color(0, 51, 102));
        bModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/Edit.png"))); // NOI18N
        bModificar.setText("Editar");
        bModificar.setName("bModificar"); // NOI18N
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bEliminar.setForeground(new java.awt.Color(0, 51, 102));
        bEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/trash.png"))); // NOI18N
        bEliminar.setText("Eliminar");
        bEliminar.setName("bEliminar"); // NOI18N
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bCancelar.setForeground(new java.awt.Color(0, 51, 102));
        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/cancel.png"))); // NOI18N
        bCancelar.setText("Cancelar");
        bCancelar.setName("bCancelar"); // NOI18N
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bSalir.setForeground(new java.awt.Color(0, 51, 102));
        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/salir.png"))); // NOI18N
        bSalir.setText("Salir");
        bSalir.setName("bSalir"); // NOI18N
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCrear)
                    .addComponent(bModificar)
                    .addComponent(bEliminar)
                    .addComponent(bCancelar)
                    .addComponent(bSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Nuevo Permiso");
        jLabel2.setName("jLabel2"); // NOI18N

        txtPermisos.setName("txtPermisos"); // NOI18N
        txtPermisos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPermisosKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Buscar");
        jLabel3.setName("jLabel3"); // NOI18N

        txtBuscarPermisos.setName("txtBuscarPermisos"); // NOI18N
        txtBuscarPermisos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarPermisosKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPermisos))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarPermisos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBuscarPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        Cancelar();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        CrearPermisos();
    }//GEN-LAST:event_bCrearActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        EditarPermiso();
    }//GEN-LAST:event_bModificarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed

        EliminarPermiso();

    }//GEN-LAST:event_bEliminarActionPerformed

    private void tbPermisosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPermisosMouseClicked
        if (evt.getClickCount() == 2) {
            if (tbPermisos.getSelectedRowCount() == 1) {
                bModificar.setText("Editar");
                bModificar.doClick();
            }
        }
    }//GEN-LAST:event_tbPermisosMouseClicked

    private void txtBuscarPermisosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPermisosKeyReleased
        BuscarCliente();
    }//GEN-LAST:event_txtBuscarPermisosKeyReleased

    private void txtPermisosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPermisosKeyPressed
        if (bCrear.isEnabled()) {
            control.passFocus(evt, bCrear);
        } else {
            control.passFocus(evt, bModificar);
        }
    }//GEN-LAST:event_txtPermisosKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPermisos;
    private javax.swing.JTextField txtBuscarPermisos;
    private javax.swing.JTextField txtPermisos;
    // End of variables declaration//GEN-END:variables
}
