/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jym.ferreteria.gui.internalframes;

import java.awt.Component;
import java.awt.Font;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

import javax.swing.text.JTextComponent;
import javax.swing.SpinnerDateModel;
import jym.ferreteria.clases.Accesos;
import jym.ferreteria.clases.Controlador;
import static jym.ferreteria.clases.Controlador.Base;
import jym.ferreteria.gui.dialogs.CobrarVentaDialog;
import jym.ferreteria.gui.dialogs.SeleccionarClienteDialog;
import jym.ferreteria.renders.CustomTableModel;
import jym.ferreteria.renders.LabelRenderer;
import jym.ferreteria.gui.FrmMain;
import jym.ferreteria.gui.dialogs.IniciarSesionAdmin;

public class FrmGestionCombos extends javax.swing.JInternalFrame {

    private CustomTableModel modeloProductoDetalle = new CustomTableModel();
    private CustomTableModel productosModel = new CustomTableModel();
    private final Controlador control = new Controlador();
    
    private final DecimalFormat format = new DecimalFormat("0.00", DecimalFormatSymbols.getInstance());
    private final DecimalFormat format2 = new DecimalFormat("0", DecimalFormatSymbols.getInstance());
    
    private String producto;
    private String UnidadA;
    private String nomProd;
    private String rubro;
    private String composicion;
    private String presentacion;
    private String laboratorio;
    private String codprod;
    private String Unidad;
     private String codProd;
    private String datos[] = null;
    
    private boolean guardado = false;
    private boolean editando = false;
    
    
    public FrmGestionCombos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscar = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cboUnidad = new javax.swing.JComboBox();
        jScrollPaneProductos = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnomCombo = new javax.swing.JTextField();
        txtcodCombo = new javax.swing.JTextField();
        txtCostoCombo1 = new javax.swing.JTextField();
        cboEstadoCombo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblProducto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPaneDetalles = new javax.swing.JScrollPane();
        tablaProductosDetalle = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JButton();
        btnEditarProducto = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnBorrarT = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gestión de Combos de Productos");

        lblBuscar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblBuscar.setText("Buscar");

        txtBuscarProducto.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtBuscarProductoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtBuscarProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarProductoFocusGained(evt);
            }
        });
        txtBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProductoActionPerformed(evt);
            }
        });
        txtBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarProductoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProductoKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Unidades");

        cboUnidad.setEnabled(false);
        cboUnidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboUnidadItemStateChanged(evt);
            }
        });
        cboUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboUnidadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cboUnidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cboUnidadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboUnidadMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cboUnidadMouseReleased(evt);
            }
        });
        cboUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUnidadActionPerformed(evt);
            }
        });
        cboUnidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboUnidadKeyPressed(evt);
            }
        });

        tablaProductos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductos.setToolTipText("");
        tablaProductos.getTableHeader().setReorderingAllowed(false);
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaProductosMousePressed(evt);
            }
        });
        tablaProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaProductosKeyPressed(evt);
            }
        });
        jScrollPaneProductos.setViewportView(tablaProductos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Elija los Productos Pertenecientes al Combo:");

        jLabel2.setText("Nombre del Combo: ");

        jLabel3.setText("Código del Combo:");

        jLabel4.setText("Costo del Combo:");

        jLabel5.setText("Estado del Combo:");

        txtCostoCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoCombo1ActionPerformed(evt);
            }
        });

        cboEstadoCombo.setForeground(new java.awt.Color(0, 51, 102));
        cboEstadoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        cboEstadoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEstadoComboItemStateChanged(evt);
            }
        });
        cboEstadoCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cboEstadoComboPopupMenuWillBecomeVisible(evt);
            }
        });
        cboEstadoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoComboActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Cantidad:");

        txtCantidad.setEditable(false);
        txtCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCantidad.setText("1");
        txtCantidad.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCantidadCaretUpdate(evt);
            }
        });
        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCantidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadFocusLost(evt);
            }
        });
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        lblProducto.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(18, 22, 82));
        lblProducto.setText(" ");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaProductosDetalle.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        tablaProductosDetalle.setForeground(new java.awt.Color(0, 51, 102));
        tablaProductosDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductosDetalle.getTableHeader().setReorderingAllowed(false);
        tablaProductosDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosDetalleMouseClicked(evt);
            }
        });
        jScrollPaneDetalles.setViewportView(tablaProductosDetalle);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Productos del Combo");

        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/trash-icon.png"))); // NOI18N
        btnEliminarProducto.setEnabled(false);
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        btnEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/pencil-icon.png"))); // NOI18N
        btnEditarProducto.setEnabled(false);
        btnEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPaneDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jScrollPaneDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/Actions-document-save-icon.png"))); // NOI18N
        btnGuardar.setMnemonic('G');
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/cancel.png"))); // NOI18N
        btnCancelar.setMnemonic('a');
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/salir.png"))); // NOI18N
        jButton1.setMnemonic('S');
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnBorrarT.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBorrarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/font_red_delete.png"))); // NOI18N
        btnBorrarT.setMnemonic('N');
        btnBorrarT.setText("Deshacer Combo");
        btnBorrarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneProductos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtcodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtnomCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboEstadoCombo, 0, 217, Short.MAX_VALUE)
                                            .addComponent(txtCostoCombo1)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnBorrarT, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtnomCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCostoCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboEstadoCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(txtcodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(cboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBuscar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBorrarT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarProductoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtBuscarProductoAncestorAdded
        //txtBuscarProducto.requestFocus();
    }//GEN-LAST:event_txtBuscarProductoAncestorAdded

    private void txtBuscarProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarProductoFocusGained
     /*   this.jScrollPaneProductos.setBorder(this.defaultBorder);
        this.jScrollPaneAlmacen.setBorder(this.defaultBorder);*/
    }//GEN-LAST:event_txtBuscarProductoFocusGained

    private void txtBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoActionPerformed

    private void txtBuscarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductoKeyPressed
        /*if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            if (this.productosModel.getRowCount() > 0) {
                try {
                    this.jScrollPaneProductos.setBorder(this.focusBorder);
                    this.jScrollPaneAlmacen.setBorder(this.defaultBorder);
                    this.tablaProductos.getSelectionModel().setSelectionInterval(0, 0);
                    this.tablaProductos.requestFocus();
                } catch (Exception e) {
                }
            }
        }*/
    }//GEN-LAST:event_txtBuscarProductoKeyPressed

    private void txtBuscarProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductoKeyReleased

       // this.cargarProductos();
    }//GEN-LAST:event_txtBuscarProductoKeyReleased

    private void cboUnidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboUnidadItemStateChanged
        //cargarProductos(); // TODO add your handling code here:
    }//GEN-LAST:event_cboUnidadItemStateChanged

    private void cboUnidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboUnidadMouseClicked
        // cargarProductos();   // TODO add your handling code here:
    }//GEN-LAST:event_cboUnidadMouseClicked

    private void cboUnidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboUnidadMouseEntered
        //cargarProductos();        // TODO add your handling code here:
    }//GEN-LAST:event_cboUnidadMouseEntered

    private void cboUnidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboUnidadMouseExited
        //cargarProductos();    // TODO add your handling code here:
    }//GEN-LAST:event_cboUnidadMouseExited

    private void cboUnidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboUnidadMousePressed
        //cargarProductos();        // TODO add your handling code here:
    }//GEN-LAST:event_cboUnidadMousePressed

    private void cboUnidadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboUnidadMouseReleased
        //cargarProductos();        // TODO add your handling code here:
    }//GEN-LAST:event_cboUnidadMouseReleased

    private void cboUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUnidadActionPerformed
        //this.cargarProductos();
        //JOptionPane.showMessageDialog(null, dato);// TODO add your handling code here:
    }//GEN-LAST:event_cboUnidadActionPerformed

    private void cboUnidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboUnidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboUnidadKeyPressed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        if (evt.getClickCount() >= 2) {
           // this.seleccionarProducto();
        }
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void tablaProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMousePressed
        //        cargarPopup(evt)
    }//GEN-LAST:event_tablaProductosMousePressed

    private void tablaProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaProductosKeyPressed
      /*  if (evt.getKeyCode() == KeyEvent.VK_ENTER && this.tablaProductos.getSelectedRow() >= 0) {
            if (this.tablaAlmacen.getRowCount() == 0) {
                this.seleccionarProducto();
            } else {

                try {
                    this.tablaAlmacen.getSelectionModel().addSelectionInterval(0, 0);
                    this.jScrollPaneProductos.setBorder(this.defaultBorder);
                    this.jScrollPaneAlmacen.setBorder(this.focusBorder);

                } catch (Exception ex) {

                }
                this.tablaAlmacen.requestFocus();
                evt.consume();
            }

        }*/
    }//GEN-LAST:event_tablaProductosKeyPressed

    private void txtCostoCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoCombo1ActionPerformed

    private void cboEstadoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEstadoComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoComboItemStateChanged

    private void cboEstadoComboPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboEstadoComboPopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoComboPopupMenuWillBecomeVisible

    private void cboEstadoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoComboActionPerformed

    private void txtCantidadCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCantidadCaretUpdate

    }//GEN-LAST:event_txtCantidadCaretUpdate

    private void txtCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusGained
      /*  if (this.txtPrecio.getText().trim().length() == 0) {
            this.txtPrecio.grabFocus();
        }*/
    }//GEN-LAST:event_txtCantidadFocusGained

    private void txtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusLost
        /*double costoProducto = 0;
        double descuento = 0;
        double cantidad = 1;

        try {
            cantidad = Double.parseDouble(this.txtCantidad.getText().replace(",", ""));
        } catch (Exception e) {
        }
        try {
            descuento = Double.parseDouble(this.txtDescuento.getText().replace(",", ""));
        } catch (Exception e) {
        }
        if (cantidad < 1) {

            this.txtPrecio.setText(this.control.decimalFormat(this.precios[0]));
            costoProducto = this.precios[1];
            costoProducto = costoProducto - descuento;
            this.indexPrecios = 0;

        } else {
            if (!this.listaUnidades.contains(this.unidadDeMedidaProducto)) {
                this.txtPrecio.setText(this.control.decimalFormat(this.precios[0]));
                costoProducto = this.precios[0];
                costoProducto = costoProducto - descuento;
                this.indexPrecios = 0;
            } else {
                this.txtPrecio.setText(this.control.decimalFormat(this.precios[1]));
                costoProducto = this.precios[1];
                costoProducto = costoProducto - descuento;
                this.indexPrecios = 1;
            }
        }*/
        //txtTotal.setText(control.decimalFormat(costoProducto * cantidad));
    }//GEN-LAST:event_txtCantidadFocusLost

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
      /*  if ((evt.getKeyChar() == KeyEvent.VK_ENTER) && (this.txtCantidad.getText().trim().length() > 0)) {
            if (this.txtDescuento.getText().trim().length()==0){
                this.txtDescuento.setText("0");
            }
            double dco=Double.parseDouble(this.txtDescuento.getText());

            if(dco<0 || dco>100){
                JOptionPane.showMessageDialog(null, "Error El Descuento debe ser ingresado en un rango numérico"
                    + " de 0 a 100");

            }
            else{
                int CantR=this.CantReal;
                double cant=Double.parseDouble(this.txtCantidad.getText());
                double prueba=0;
                prueba=CantR*cant;
                if(prueba%1==0 && prueba>0){
                    int cantVenta=(int)prueba;
                    double cantLoteFis=Double.parseDouble(txtCantLote.getText());
                    int cantLote=(int)cantLoteFis;
                    if(cantVenta>cantLote){
                        JOptionPane.showMessageDialog(this, "La Cantidad Total de Unidades ingresada supera a la cantidad del Lote, por favor seleccione a lo sumo la misma cantidad del lote, \n"
                            + " y si desea mas productos similares, cargue luego el mismo producto de otros lotes");
                        this.txtCantidad.requestFocus();
                    }
                    else{
                        if (this.idVenta == 0) {
                            this.guardar();

                        }
                        this.agregarProducto();
                        //System.out.println("2");
                        this.guardar();
                        //System.out.println("3");
                    }

                }
                else{
                    JOptionPane.showMessageDialog(this, "La Cantidad Asignada es Incorrecta");
                    this.txtCantidad.requestFocus();
                }
            }
        }*/
    }//GEN-LAST:event_txtCantidadKeyPressed

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        //this.calcularCostoPorProducto();        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
//        control.decimal(evt, this.txtCantidad.getText());
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void tablaProductosDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosDetalleMouseClicked
       /* this.btnEditarProducto.setEnabled(true);
        this.btnEliminarProducto.setEnabled(true);
        if (evt.getClickCount() > 1 && !this.facturado) {
            this.cargarEditar();
        }*/
    }//GEN-LAST:event_tablaProductosDetalleMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
/*        if (this.cliente != null) {
            this.guardar();
            JOptionPane.showMessageDialog(this, "La venta se ha guardado correctamente");
            if (this.listadoVentas != null) {
                listadoVentas.recargar();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione el cliente para la venta");
        }*/
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        //eliminartodo();
       /* this.producto = null;
        this.editando=false;
        this.lblProducto.setText(" ");
        this.lblAlmacen.setText(" ");
        this.txtCantidad.setText("1");
        this.txtDescuento.setText("0.00");
        this.txtPrecio.setText("0.00");
        this.txtCantidad.setEditable(false);
        this.txtPrecio.setEditable(false);
        this.txtDescuento.setEditable(false);
        this.tablaProductosDetalle.setEnabled(true);
        this.txtBuscarDetalle.setEnabled(true);
        this.jScrollPaneProductos.setBorder(defaultBorder);
        this.jScrollPaneAlmacen.setBorder(defaultBorder);
        this.txtBuscarProducto.setText("");
        this.txtBuscarDetalle.setText("");
        this.txtBuscarDetalle.requestFocus();
        this.cboUnidad.setSelectedIndex(0);*/
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*if(!guardado){
            if(modeloProductoDetalle.getRowCount()==0){
                control.ejecutar(String.format("DELETE FROM venta WHERE `idVenta`=%s;", idVenta));
                btnNuevo.doClick();
                this.dispose();
            }else{
                eliminartodo();
                control.ejecutar(String.format("DELETE FROM venta WHERE `idVenta`=%s;", idVenta));
                btnNuevo.doClick();

            }
        }
        */
      //  this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBorrarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTActionPerformed
       /* if (JOptionPane.showInternalConfirmDialog(this, "¿Confirma que deseal eliminar toda la Lista de productos vendidos e Iniciar una Nueva Venta?", "Mensaje", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
            this.eliminartodo();
            this.guardar();
        }  */      // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarTActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
     /*   if (!this.facturado) {
            this.eliminarLinea();
            this.guardar();
        } else {
            JOptionPane.showMessageDialog(this, "Ya se ha generado un comprobante para esta venta, no se pueden eliminar los productos", "Mensaje", 2);
        }*/
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProductoActionPerformed
      /*  if (!facturado) {
            //eliminarLinea();
            this.guardar();

            this.cargarEditar();
        } else {
            JOptionPane.showMessageDialog(this, "Ya se ha generado un comprobante para esta venta, ya no se pueden modificar los productos");
        }*/
    }//GEN-LAST:event_btnEditarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarT;
    private javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEditarProducto;
    public javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnGuardar;
    public static javax.swing.JComboBox cboEstadoCombo;
    private javax.swing.JComboBox cboUnidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneDetalles;
    private javax.swing.JScrollPane jScrollPaneProductos;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JTable tablaProductos;
    public javax.swing.JTable tablaProductosDetalle;
    public javax.swing.JTextField txtBuscarProducto;
    public javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCostoCombo1;
    private javax.swing.JTextField txtcodCombo;
    private javax.swing.JTextField txtnomCombo;
    // End of variables declaration//GEN-END:variables
}
