/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jym.ferreteria.gui.internalframes;

import java.awt.Font;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import jym.ferreteria.clases.Controlador;
import jym.ferreteria.renders.CustomTableModel;
import jym.ferreteria.renders.LabelRenderer;
import jym.ferreteria.renders.LabelRenderer;
import jym.ferreteria.renders.LateralTableHeader;

/**
 *
 * @author Omr
 */
public class FrmProductosBajosDeStock extends javax.swing.JInternalFrame {

    private static Controlador controlador = new Controlador();
    private static CustomTableModel model = new CustomTableModel();

    /**
     * Creates new form ProductosStockMinimo
     */
    public FrmProductosBajosDeStock() {
        initComponents();

        this.setFrameIcon(new ImageIcon(this.getClass().getResource(Controlador.ICON_PATH)));
        model.setColumnIdentifiers(new String[]{"N°","Codigo", "Nombre","Rubro","Composición","Presentación","Laboratorio", "Und", "Almacén", "Stock mínimo", "Stock disponible"});
        jTable1.setModel(model);
         jTable1.setDefaultRenderer(Object.class, new LabelRenderer());
        jTable1.getColumnModel().getColumn(0).setCellRenderer(new LateralTableHeader());
        controlador.tableWidthColumn(jTable1, 50, 0);
        controlador.tableWidthColumn(jTable1, 300, 2);
         controlador.tableWidthColumn(jTable1, 180, 3,4,5,6);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        controlador.tableMaxWidthColumn(jTable1, 100, 7, 8);
        controlador.tableMaxWidthColumn(jTable1, 150, 9, 10);
       LabelRenderer labelRenderer = new LabelRenderer(SwingConstants.RIGHT);
        jTable1.getColumnModel().getColumn(9).setCellRenderer(labelRenderer);
        jTable1.getColumnModel().getColumn(10).setCellRenderer(labelRenderer);
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBus = new javax.swing.JTextField();

        FormListener formListener = new FormListener();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Productos bajos de stock");
        setPreferredSize(new java.awt.Dimension(1400, 500));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/salir.png"))); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(formListener);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/Print.png"))); // NOI18N
        jButton2.setText("Imprimir");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(formListener);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Buscar: ");
        jLabel1.setName("jLabel1"); // NOI18N

        txtBus.setName("txtBus"); // NOI18N
        txtBus.addKeyListener(formListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1384, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBus, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(txtBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.KeyListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == jButton1) {
                FrmProductosBajosDeStock.this.jButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                FrmProductosBajosDeStock.this.jButton2ActionPerformed(evt);
            }
        }

        public void keyPressed(java.awt.event.KeyEvent evt) {
        }

        public void keyReleased(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == txtBus) {
                FrmProductosBajosDeStock.this.txtBusKeyReleased(evt);
            }
        }

        public void keyTyped(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == txtBus) {
                FrmProductosBajosDeStock.this.txtBusKeyTyped(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Map map = new HashMap();
        map.put("bus", txtBus.getText());
        controlador.showReportDialog("Productos bajos de stock", "productosBajosDeStock", map);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusKeyTyped
     // TODO add your handling code here:
    }//GEN-LAST:event_txtBusKeyTyped

    private void txtBusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusKeyReleased
      cargarDatos1();     // TODO add your handling code here:
    }//GEN-LAST:event_txtBusKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBus;
    // End of variables declaration//GEN-END:variables

    public  static void cargarDatos() {
        String bus="";
     
        controlador.LlenarJTabla(model, "select p.idProduto,p.codUnid, p.nomproducto, c.nomtip, p.composicion, pre.present, m.nommarc, un.nomuniddes, a.nombre, \n " +
"p.stockMinimo, s.cantidadDisponible \n " +
"from produto p \n " +
"inner join tipoproducto c on c.idTipoProducto=p.idTipoProducto \n " +
"inner join presentacion pre on pre.idPresentacion=p.idPresentacion \n " +
"inner join marca m on m.idmarca=p.idmarca \n " +
"inner join detunidprod u on u.idproducto=p.idproduto and idUnidades='1' \n " +
"inner join unidades un on un.idUnidades=u.idunidades \n " +
"inner join stock s on s.idProducto=p.idproduto \n " +
"inner join almacen a on a.idalmacen=s.idAlmacen \n "
                + "WHERE  s.`cantidadDisponible`<=p.`stockMinimo`  ORDER BY p.`idproduto`;", 11);

    }
    
    public  void cargarDatos1() {
        String bus="";
        bus=txtBus.getText();
        controlador.LlenarJTabla(model, "select p.idProduto,p.codUnid, p.nomproducto, c.nomtip, p.composicion, pre.present, m.nommarc, un.nomuniddes, a.nombre, \n " +
"p.stockMinimo, s.cantidadDisponible \n " +
"from produto p \n " +
"inner join tipoproducto c on c.idTipoProducto=p.idTipoProducto \n " +
"inner join presentacion pre on pre.idPresentacion=p.idPresentacion \n " +
"inner join marca m on m.idmarca=p.idmarca \n " +
"inner join detunidprod u on u.idproducto=p.idproduto and idUnidades='1' \n " +
"inner join unidades un on un.idUnidades=u.idunidades \n " +
"inner join stock s on s.idProducto=p.idproduto \n " +
"inner join almacen a on a.idalmacen=s.idAlmacen \n "
                + "WHERE  s.`cantidadDisponible`<=p.`stockMinimo` and (p.codUnid like '%"+bus+"%' or p.nomproducto like '%"+bus+"%' or m.nommarc like '%"+bus+"%') group by p.idProduto, a.idAlmacen ORDER BY p.`idproduto`;", 11);

    }

}
