/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jym.ferreteria.gui.internalframes;

import jym.ferreteria.gui.internalframes.FrmListadoFacturas;
import jym.ferreteria.gui.dialogs.SeleccionarProveedorDialog;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import jym.ferreteria.clases.Configuracion;
import jym.ferreteria.clases.Controlador;
// reporte por cuenta

/**
 *
 * @author Omr
 */
public class FrmRegistrarFacturaProveedor extends javax.swing.JInternalFrame {

    private Controlador control = new Controlador();
    private SeleccionarProveedorDialog seleccionarProveedor;
    private String proveedor;
    private final FrmListadoFacturas listadoFacturas;
    private String idFactura;
    private Map map = new HashMap();

    /**
     * Creates new form RegistrarFacturaProveedor
     */
    public FrmRegistrarFacturaProveedor(FrmListadoFacturas listadoFacturas) {
        initComponents();
        this.setFrameIcon(new ImageIcon(this.getClass().getResource(Controlador.ICON_PATH)));
        this.listadoFacturas = listadoFacturas;
        control.fillComboBox("SELECT `idTipoComprobante`, `nombre` FROM `tipocomprobante` WHERE `paraVenta`=FALSE ORDER BY `nombre`;", cboComprobante, map);
        txtFecha.setDate(new Date());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtProveedor = new javax.swing.JTextField();
        btnProveedor = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtMontoTotal = new javax.swing.JTextField();
        txtObservaciones = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboComprobante = new javax.swing.JComboBox();
        cboMoneda = new javax.swing.JComboBox();

        FormListener formListener = new FormListener();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar Facturas de Proveedor");

        btnSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/salir.png"))); // NOI18N
        btnSalir.setMnemonic('S');
        btnSalir.setText("Salir");
        btnSalir.setName("btnSalir"); // NOI18N
        btnSalir.addActionListener(formListener);

        btnAceptar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/registrar.png"))); // NOI18N
        btnAceptar.setMnemonic('A');
        btnAceptar.setText("Aceptar");
        btnAceptar.setName("btnAceptar"); // NOI18N
        btnAceptar.addActionListener(formListener);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Proveedor:");
        jLabel4.setName("jLabel4"); // NOI18N

        txtProveedor.setEditable(false);
        txtProveedor.setName("txtProveedor"); // NOI18N
        txtProveedor.setNextFocusableComponent(btnProveedor);

        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jym/ferreteria/imagenes/SEO-icon.png"))); // NOI18N
        btnProveedor.setName("btnProveedor"); // NOI18N
        btnProveedor.setNextFocusableComponent(txtSerie);
        btnProveedor.addActionListener(formListener);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Serie: ");
        jLabel1.setName("jLabel1"); // NOI18N

        txtSerie.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtSerie.setName("txtSerie"); // NOI18N
        txtSerie.setNextFocusableComponent(txtNumero);
        txtSerie.addKeyListener(formListener);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Número: ");
        jLabel2.setName("jLabel2"); // NOI18N

        txtNumero.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtNumero.setName("txtNumero"); // NOI18N
        txtNumero.setNextFocusableComponent(txtMontoTotal);
        txtNumero.addKeyListener(formListener);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Fecha: ");
        jLabel3.setName("jLabel3"); // NOI18N

        txtFecha.setDateFormatString("dd/MM/yyyy");
        txtFecha.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtFecha.setName("txtFecha"); // NOI18N
        txtFecha.setNextFocusableComponent(btnAceptar);
        txtFecha.addKeyListener(formListener);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Monto:");
        jLabel5.setName("jLabel5"); // NOI18N

        txtMontoTotal.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtMontoTotal.setText("0.00");
        txtMontoTotal.setName("txtMontoTotal"); // NOI18N
        txtMontoTotal.setNextFocusableComponent(txtFecha);
        txtMontoTotal.addKeyListener(formListener);

        txtObservaciones.setName("txtObservaciones"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Obs.");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Comprobante: ");
        jLabel7.setName("jLabel7"); // NOI18N

        cboComprobante.setName("cboComprobante"); // NOI18N

        cboMoneda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S/", "$" }));
        cboMoneda.setName("cboMoneda"); // NOI18N
        cboMoneda.addKeyListener(formListener);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboMoneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cboComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProveedor)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProveedor))
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.KeyListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == btnSalir) {
                FrmRegistrarFacturaProveedor.this.btnSalirActionPerformed(evt);
            }
            else if (evt.getSource() == btnAceptar) {
                FrmRegistrarFacturaProveedor.this.btnAceptarActionPerformed(evt);
            }
            else if (evt.getSource() == btnProveedor) {
                FrmRegistrarFacturaProveedor.this.btnProveedorActionPerformed(evt);
            }
        }

        public void keyPressed(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == txtSerie) {
                FrmRegistrarFacturaProveedor.this.txtSerieKeyPressed(evt);
            }
            else if (evt.getSource() == txtNumero) {
                FrmRegistrarFacturaProveedor.this.txtNumeroKeyPressed(evt);
            }
            else if (evt.getSource() == txtFecha) {
                FrmRegistrarFacturaProveedor.this.txtFechaKeyPressed(evt);
            }
            else if (evt.getSource() == txtMontoTotal) {
                FrmRegistrarFacturaProveedor.this.txtMontoTotalKeyPressed(evt);
            }
            else if (evt.getSource() == cboMoneda) {
                FrmRegistrarFacturaProveedor.this.cboMonedaKeyPressed(evt);
            }
        }

        public void keyReleased(java.awt.event.KeyEvent evt) {
        }

        public void keyTyped(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == txtMontoTotal) {
                FrmRegistrarFacturaProveedor.this.txtMontoTotalKeyTyped(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        aceptar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed

        if (seleccionarProveedor == null) {
            seleccionarProveedor = new SeleccionarProveedorDialog(null, true);
        }
        seleccionarProveedor.setLocationRelativeTo(null);
        seleccionarProveedor.setVisible(true);
        String[] datos = seleccionarProveedor.getDatos();
        if (datos != null) {
            proveedor = datos[0];
            txtProveedor.setText(datos[2]);
            txtSerie.requestFocus();
        }
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void txtMontoTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoTotalKeyTyped
        control.decimal(evt, txtMontoTotal.getText());
    }//GEN-LAST:event_txtMontoTotalKeyTyped

    private void txtSerieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerieKeyPressed
        control.passFocus(evt, txtNumero);
    }//GEN-LAST:event_txtSerieKeyPressed

    private void txtNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyPressed
        control.passFocus(evt, txtMontoTotal);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtMontoTotal.selectAll();
        }
    }//GEN-LAST:event_txtNumeroKeyPressed

    private void txtMontoTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoTotalKeyPressed
        control.passFocus(evt, cboMoneda);
    }//GEN-LAST:event_txtMontoTotalKeyPressed

    private void txtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyPressed
        control.passFocus(evt, btnAceptar);
    }//GEN-LAST:event_txtFechaKeyPressed

    private void cboMonedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboMonedaKeyPressed
        control.passFocus(evt, ((JTextField) txtFecha.getDateEditor()));
    }//GEN-LAST:event_cboMonedaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cboComprobante;
    private javax.swing.JComboBox cboMoneda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtMontoTotal;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables

    private void aceptar() {
        double tasaDeCambio = Configuracion.getInstance().getTasaDeCambio();
        if (cboMoneda.getSelectedIndex() == 0) {
            tasaDeCambio = 1;
        }
        if (proveedor != null) {
            if (txtSerie.getText().trim().length() > 0 && txtNumero.getText().trim().length() > 0) {
                if (txtFecha.getDate() != null) {
                    double monto = 0;
                    try {
                        monto = Double.parseDouble(txtMontoTotal.getText());
                    } catch (Exception e) {
                    }
                    if (monto > 0) {
                        monto = monto * tasaDeCambio;
                        if (idFactura == null) {//Registrando nueva factura
                            boolean b = control.ejecutar(String.format("INSERT INTO facturaproveedor VALUES(NULL,%s,'%s','%s','%s',0,%s,'%s',%s,%s,%s);", proveedor, txtSerie.getText(), txtNumero.getText(), control.Formato_Amd(txtFecha.getDate()), txtMontoTotal.getText(), txtObservaciones.getText(), map.get(cboComprobante.getSelectedIndex()), monto, cboMoneda.getSelectedIndex() == 0));
                            if (b) {
                                if (listadoFacturas != null) {
                                    listadoFacturas.recargar();
                                    this.dispose();
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Ocurrió un error al procesar los datos", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {//Modificando Factura

                            boolean b = control.ejecutar(String.format("UPDATE facturaproveedor f SET "
                                    + "f.`idProveedor`=%s, "
                                    + "f.`serie`='%s', "
                                    + "f.`numero`='%s', "
                                    + "f.`fecha`='%s', "
                                    + "f.`total`=%s, "
                                    + "f.`totalSoles`=%s, "
                                    + "f.`enSoles`=%s, "
                                    + "f.`observaciones`='%s', "
                                    + "f.`idTipoComprobante`=%s "
                                    + "WHERE f.`idFacturaProveedor`=%s;", proveedor, txtSerie.getText(), txtNumero.getText(), control.Formato_Amd(txtFecha.getDate()), txtMontoTotal.getText(), monto, cboMoneda.getSelectedIndex() == 0, txtObservaciones.getText(), map.get(cboComprobante.getSelectedIndex()), idFactura));
                            if (b) {
                                if (listadoFacturas != null) {
                                    listadoFacturas.recargar();
                                    this.dispose();
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Ocurrió un error al procesar los datos", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "El monto de la factura debe de ser mayo a cero", "Aviso", JOptionPane.WARNING_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Debe indicar la fecha de facturación", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese la serie y el número de la factura del proveedor", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione el proveedor, para asignar la factura correspondiente", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

    }

    void setId(String idFactura) {
        this.idFactura = idFactura;
        String[] datos = control.cargarRegistro("SELECT f.`serie`, f.`numero`, date_format(f.`fecha`,'%d/%m/%Y') as fecha, f.`total`, f.`idProveedor`, p.`Nombre`, f.`observaciones`, t.`nombre`, f.`enSoles` "
                + "FROM facturaproveedor f, proveedor p, tipocomprobante t "
                + "WHERE p.`idProveedor`=f.`idProveedor` AND f.`idTipoComprobante`=t.`idTipoComprobante` AND f.`idFacturaProveedor`=" + idFactura, 9);
        txtSerie.setText(datos[0]);
        txtNumero.setText(datos[1]);
        txtMontoTotal.setText(datos[3]);
        ((JTextField) txtFecha.getDateEditor()).setText(datos[2]);
        proveedor = datos[4];
        txtProveedor.setText(datos[5]);
        txtObservaciones.setText(datos[6]);
        cboComprobante.setSelectedItem(datos[7]);
        cboMoneda.setSelectedIndex("1".equals(datos[8]) ? 0 : 1);
    }

}
